In [1]:
%run features_spectral.ipynb
%run load_labels.ipynb

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import keras
from keras.models import load_model
from keras import backend as K
from keras import models
from keras.layers import Dense
import tensorflow as tf
from tensorflow.keras.utils import to_categorical


In [3]:
num_classes = 2
channels = 32
sfreq = 128

In [4]:
data = dataset = load_dataset(raw=False)
data = convert_to_epochs(dataset, channels, sfreq)
data = data.reshape((data.shape[0], data.shape[1]*data.shape[2])) # IS THIS THE CORRECT CONVERSION FROM 3D TO 2D?

In [5]:
epochs = dataset.shape[2]//sfreq

In [6]:

labels = load_labels()
label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
label = label.repeat(epochs)

# KNN Classifier

In [7]:
K.clear_session()
x_train, x_test, y_train, y_test = train_test_split(
    data, label, test_size=0.33, random_state=42)
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
neigh_clf = KNeighborsClassifier(n_neighbors=2)
neigh_clf.fit(x_train, y_train)
y_pred = neigh_clf.predict(x_test)
y_true = y_test


In [8]:
scores_neigh = neigh_clf.score(x_test, y_test)
precision_neigh = metrics.precision_score(y_true, y_pred, average='macro')
recall_neigh = metrics.recall_score(y_true, y_pred, average='micro')
f1_score_neigh = metrics.f1_score(y_true, y_pred, average='weighted')
print('accuracy is:', scores_neigh)
print('precision is:', precision_neigh)
print('recall is:', recall_neigh)
print('f1_score is:', f1_score_neigh)
metrics.confusion_matrix(y_true, y_pred)


accuracy is: 0.5323232323232323
precision is: 0.26616161616161615
recall is: 0.5323232323232323
f1_score is: 0.36985411131752594


/opt/homebrew/Caskroom/miniforge/base/envs/init/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[527,   0],
       [463,   0]])

# SVM Classifier

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    data, label, test_size=0.33, random_state=42)
svm_clf = SVC()
svm_clf.fit(x_train, y_train)
y_pred = svm_clf.predict(x_test)
y_true = y_test


In [10]:
scores_svm = svm_clf.score(x_test, y_test)
precision_svm = metrics.precision_score(y_true, y_pred, average='macro')
recall_svm = metrics.recall_score(y_true, y_pred, average='micro')
f1_score_svm = metrics.f1_score(y_true, y_pred, average='weighted')
print('accuracy is:', scores_svm)
print('precision is:', precision_svm)
print('recall is:', recall_svm)
print('f1_score is:', f1_score_svm)
metrics.confusion_matrix(y_true, y_pred)


accuracy is: 0.5191919191919192
precision is: 0.5149193128578865
recall is: 0.5191919191919192
f1_score is: 0.5172700672700672


array([[308, 219],
       [257, 206]])

# Neural Network

In [11]:
K.clear_session()
y_v = label
y_v = to_categorical(y_v, num_classes)
x_train, x_test, y_train, y_test = train_test_split(
    data, y_v, test_size=0.33, random_state=42)

In [12]:
x_in = keras.Input(shape=(x_train.shape[1],))
x = Dense(500, kernel_initializer='normal', activation='relu')(x_in)
x = Dense(300, kernel_initializer='normal', activation='relu')(x)
x = Dense(200, kernel_initializer='normal', activation='relu')(x)
x = Dense(50, kernel_initializer='normal', activation='relu')(x)
out_layer = Dense(num_classes, activation='softmax', name='out')(x)
model = keras.Model(x_in, out_layer)
#         model.summary()
# Compile model
#         loss_fn = keras.losses.SparseCategoricalCrossentropy()
#         loss_fn = keras.losses.categorical_crossentropy()

Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB



2022-10-06 09:59:23.746502: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-06 09:59:23.746909: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [13]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
#model.summary()
# Fit the model
model.fit(x_train, y_train, epochs=100, batch_size=128, verbose=0)
# evaluate the model
scores_dnn = model.evaluate(x_test, y_test, verbose=0)

2022-10-06 09:59:23.890218: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-10-06 09:59:24.102093: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-06 09:59:37.602838: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [14]:
y_pred = model.predict(x_test)
y_true = y_test
y_pred = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_true, axis=1)

31/31 [==============================] - 0s 2ms/step


2022-10-06 09:59:37.931766: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [15]:
precision_dnn = metrics.precision_score(y_true, y_pred, average='macro')
recall_dnn = metrics.recall_score(y_true, y_pred, average='micro')
f1_score_dnn = metrics.f1_score(y_true, y_pred, average='weighted')
print('accuracy is:', scores_dnn[1])
print('precision is:', precision_dnn)
print('recall is:', recall_dnn)
print('f1_score is:', f1_score_dnn)
metrics.confusion_matrix(y_true, y_pred)

accuracy is: 0.4929293096065521
precision is: 0.49025367156208277
recall is: 0.49292929292929294
f1_score is: 0.4926297053471087


array([[280, 247],
       [255, 208]])